### ISSUE TITLE
"Couldn't find iPhone Simulator message" results crash with iOS SDK 4.2 and iPhone simulator 4

### ISSUE THREAD

**Issue by exalted** [lorenbrichter/SimFinger#10]
1. Changed all xcodeproj SDK's to _latest_ (newly introduced with Xcode 3.2.5): iOS 4.2 and Mac OS X 10.6
2. Compiled with `for i in $(find . -name '*.xcodeproj'); do xcodebuild -project $i -configuration Release build; done`
3. Launched `~/Downloads/SimFinger/Fake/SimFinger/build/Release/SimFinger`
4. Main window seems come up fine with an iPhone4 frame, but regardless if simulator is running or not, SimFinger will say **Couldn't find iPhone Simulator** _twice_ and crash.

Console output goes like this:

`2010-11-30 10:53:18.208 SimFinger[14307:a0f] +[FakeFingerAppDelegate countByEnumeratingWithState:objects:count:]: unrecognized selector sent to class 0x711c`

`2010-11-30 10:53:18.256 SimFinger[14307:a0f] +[FakeFingerAppDelegate countByEnumeratingWithState:objects:count:]: unrecognized selector sent to class 0x711c`

I may provide more detailed output on this issue, please let me know.

Best regards,
Ali Servet Donmez
http://www.pittle.org/

**Comment by ygbr** [comment]
same problem here!

**Comment by raphaelokon** [comment]
Same here.

**Comment by kpbode** [comment]
Just add a dash in line 52 of FakeFingerAppDelegate to the NSApplicationName to make it "iOS-Simulator"

**Comment by raphaelokon** [comment]
I've done it just a minute ago and it worked perfectly for me. But the overlay window still stick on the left side of my screen.

**Comment by napoleone1981** [comment]
Well, the real fix is to put, on the line kpbode told us, the real name of iOS Simulator app... in other words, what you see on the Mac menu bar.
In italian the fix is "Simulatore iOS"...

**Comment by cocoacoder** [comment]
I tried "iOS Simulator" and "iOS-Simulator", neither of which removed the error.

**Comment by kpbode** [comment]
@cocoacoder Do you have the simulator running? "iOS Simulator" works for me with SDK 5.0 installed...

**Comment by cocoacoder** [comment]
Yup, latest build on everything. I'm an iOS developer working on an iOS 5 app and running that SDK.

**Comment by nick** [comment]
You need to make sure the iOS simulator is running as a separate process before you build SimFinger. SimFinger adds an extra layer over the top of the existing iOS Simulator process.
